{% set name = "RCK" %}
{% set version = "1.0.0a3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/44/12/8c662b2c6e1e0d2939ca95dec4154b786a900c453f4dc5c6757f8def2426/RCK-1.0.0a2.tar.gz
  sha256: 64f6e7343416ab33b2b01988f14853ea55b173c9d563fbc18f473f78d4e5e413

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - networkx >=2
    - scipy
    - pyvcf
    - pysam
    - sortedcontainers
    - pandas
    - gurobi
    - pip
    - gffutils
    - python >=3.6
  run:
    - networkx >=2
    - scipy
    - pyvcf
    - pysam
    - sortedcontainers
    - pandas
    - gurobi
    - pip
    - gffutils
    - python >=3.6

test:
  imports:
    - rck
    - rck.core
    - rck.utils
    - rck.utils.adj
    - rck.utils.scn
  commands:
    - rck --help  # [not win]
    - rck-adj-x2rck --help  # [not win]
    - rck-adj-x2rck sniffles --help # [not win]
    - rck-adj-x2rck lumpy --help  # [not win]
    - rck-adj-x2rck longranger --help # [not win]
    - rck-adj-x2rck naibr --help  # [not win]
    - rck-adj-x2rck manta --help  # [not win]
    - rck-adj-x2rck grocsv --help # [not win]
    - rck-adj-x2rck delly --help  # [not win]
    - rck-adj-x2rck pbsv --help # [not win]
    - rck-adj-x2rck remixt --help # [not win]
    - rck-adj-process --help # [not win]
    - rck-adj-process cat --help  # [not win]
    - rck-adj-process reciprocal --help # [not win]
    - rck-adj-process filter --help # [not win]
    - rck-scnt-x2rck --help # [not win]
    - rck-scnt-x2rck titan --help # [not win]
    - rck-scnt-x2rck battenberg --help  # [not win]
    - rck-scnt-x2rck hatchet --help # [not win]
    - rck-scnt-x2rck remixt --help  # [not win]
    - rck-scnt-process --help # [not win]
    - rck-scnt-process refine --help # [not win]
    - rck-scnt-process align --help # [not win]
    - rck-scnt-process distance --help # [not win]
    - rck-scnb --help # [not win]
    - rck-input-refine --help # [not win]

about:
  home: https://github.com/aganezov/rck

extra:
  recipe-maintainers:
    - aganezov
