{% set name = "RCK" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/fd/85/69c8ba6c6e80e9d9acbb40365601ee0632f8ce7c8b61e051249a8db70595/RCK-1.1.0.tar.gz
  sha256: 522e7965be2eb3ed7089b37e05bb795846a7f78ec658815ad229779cd4874ca5

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - networkx >=2
    - scipy
    - pyvcf
    - pysam
    - sortedcontainers
    - pandas
    - gurobi
    - pip
    - gffutils
    - python >=3.6
  run:
    - networkx >=2
    - scipy
    - pyvcf
    - pysam
    - sortedcontainers
    - pandas
    - gurobi
    - pip
    - gffutils
    - python >=3.6

test:
  imports:
    - rck
    - rck.core
    - rck.utils
    - rck.utils.adj
    - rck.utils.scn
  commands:
    - rck --help  # [not win]
    - rck-adj-x2rck --help  # [not win]
    - rck-adj-x2rck sniffles --help # [not win]
    - rck-adj-x2rck lumpy --help  # [not win]
    - rck-adj-x2rck longranger --help # [not win]
    - rck-adj-x2rck naibr --help  # [not win]
    - rck-adj-x2rck manta --help  # [not win]
    - rck-adj-x2rck grocsvs --help # [not win]
    - rck-adj-x2rck delly --help  # [not win]
    - rck-adj-x2rck pbsv --help # [not win]
    - rck-adj-x2rck remixt --help # [not win]
    - rck-adj-process --help # [not win]
    - rck-adj-process cat --help  # [not win]
    - rck-adj-process reciprocal --help # [not win]
    - rck-adj-process filter --help # [not win]
    - rck-scnt-x2rck --help # [not win]
    - rck-scnt-x2rck titan --help # [not win]
    - rck-scnt-x2rck battenberg --help  # [not win]
    - rck-scnt-x2rck hatchet --help # [not win]
    - rck-scnt-x2rck remixt --help  # [not win]
    - rck-scnt-process --help # [not win]
    - rck-scnt-process refine --help # [not win]
    - rck-scnt-process align --help # [not win]
    - rck-scnt-process distance --help # [not win]
    - rck-scnb --help # [not win]
    - rck-input-refine --help # [not win]

about:
  home: https://github.com/aganezov/rck

extra:
  recipe-maintainers:
    - aganezov
